version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - gosec
    - govet
    - ineffassign
    - misspell
  exclusions:
    rules:
      - path: 'main.go'
        text: 'G114: Use of net/http serve function that has no support for setting timeouts'
formatters:
  enable:
    - gofmt
    - goimports
